spring:
  config:
    activate:
      on-profile: prod
#  datasource:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # 운영 환경에서는 스키마 검증만 수행
  data:
    redis:
      host: localhost # redis host
      port: 16379     # redis port

springdoc:
  cache:
    disabled: false              # 캐시 사용 여부

jwt:
  key: 20acb88d4cd80924cac42d9e4b0a903662b0abf58a12b53eacf75375d08038c6 # sample

logging:
  level:
    root: info