spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          github:

          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
#          apple:
#            client-id: your-apple-client-id
#            client-secret: your-apple-client-secret
#            scope: name, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Apple


decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    root: info
    org:
      springframework:
        jdbc: debug
